name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install FUSE
      run: sudo apt install fuse libfuse-dev pkg-config -y
    - name: Build
      run: cargo build --verbose
    - name: Grant Permission on /tmp
      run: sudo chmod -R 777 /tmp
    - name: Add user_allow_other to /etc/fuse.conf
      run: echo "user_allow_other" | sudo tee -a /etc/fuse.conf
    - name: Run tests
      run: cargo test --verbose -- --test-threads=1
  clippy_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install FUSE
      run: sudo apt install fuse libfuse-dev pkg-config -y
    - uses: actions-rs/toolchain@v1
      with:
        components: clippy
    - uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-features